/*
 * @Author: LIU CHENG 
 * @Date: 2017-02-23 14:45:13 
 * @Last Modified by: LIU CHENG
 * @Last Modified time: 2017-02-25 10:37:50
 */


export const TYPE = {
  FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',

  TYPING_USERNAME: 'TYPING_USERNAME',

  FETCH_USER_REPOS_REQUEST: 'FETCH_USER_REPOS_REQUEST',
  FETCH_USER_REPOS_SUCCESS: 'FETCH_USER_REPOS_SUCCESS',
  FETCH_USER_REPOS_FAILURE: 'FETCH_USER_REPOS_FAILURE',
  
  FETCH_NOTES_REQUEST: 'FETCH_NOTES_REQUEST',
  FETCH_NOTES_SUCCESS: 'FETCH_NOTES_SUCCESS',
  FETCH_NOTES_FAILURE: 'FETCH_NOTES_FAILURE',

  ADD_NOTE_REQUEST: 'ADD_NOTE_REQUEST',
  ADD_NOTE_SUCCESS: 'ADD_NOTE_SUCCESS',
  ADD_NOTE_FAILURE: 'ADD_NOTE_FAILURE',
}